### ISSUE TITLE
Help trying to discover slackin

### ISSUE THREAD

**Issue by px3l** [codeformuenster/slackin-docker#3]
Hi there,

Apologies I am a bit of a noob here.. I can deploy this image on a remote server via Dockerhub fine, but when it is installed, how do I find the exposed port?

Thanks!

**Comment by chk1** [comment]
Slackin runs on port 3000 by default, so you will need to map to port 3000 wth the `-p` parameter

If you run this through `docker-compose` then the public facing port will be 3000 as well, this is defined in [docker-compose.yml](https://github.com/codeformuenster/slackin-docker/blob/master/docker-compose.yml#L7).

**Comment by px3l** [comment]
ah ok perfect thank you for your clarification!
